import {
  ProductItem,
  AssemblyStepData,
  FeatureData,
  GalleryItem,
  WebsiteContentData,
  OrderItem,
  CustomerMessage,
  AppSettings,
} from '../types/data';

export const INITIAL_PRODUCT: ProductItem = {
  id: 'aura-w-cyan',
  name: 'AURA W',
  title: 'Цэнхэр Акрилик Премиум Hookah',
  description: 'Тунгалаг цэнхэр акрилик W хэлбэрийн их бие, 304 зэвэрдэггүй ган металл холбогч, болор талст аяга болон гэрэлтүүлэг бүхий тансаг зэрэглэлийн hookah.',
  price: 890000,
  currency: '₮',
  heroImage: '/src/assets/images/hookah_hero_cyan_1791448575618.jpg',
  galleryImages: [
    '/src/assets/images/hookah_hero_cyan_1791448575618.jpg',
    '/src/assets/images/hookah_crystal_bowl_1791448601777.jpg',
  ],
  status: 'active',
  material: 'Оптик зэрэглэлийн PMMA Акрилик & 304 Зэвэрдэггүй ган',
  dimensions: '480 × 280 × 90 мм',
  weight: '2,850 гр',
  stock: 14,
};

export const INITIAL_ASSEMBLY_STEPS: AssemblyStepData[] = [
  {
    id: 'body',
    stepNumber: 1,
    title: 'W Хэлбэрт Акрилик Их Бие',
    componentName: 'Акрилик Их Бие',
    shortLabel: 'ИХ БИЕ',
    subtitle: 'Давхар тасалгаат геометрийн архитектур',
    description: '12мм зузаантай, өндөр тунгалаг чанарын PMMA акриликийг W хэлбэрээр нарийн зүсэж урласан. Доод хэсэгтээ өнгө хувиргагч LED гэрэлтүүлгийн суурьтай.',
    material: 'Оптик PMMA Акрилик (12мм хана)',
    specs: '750мл багтаамж · Цохилтод тэсвэртэй · 1,420 гр',
    animationType: 'fade-up-settle',
    order: 1,
  },
  {
    id: 'connectors',
    stepNumber: 2,
    title: 'Нарийвчлалтай Металл Холбогчид',
    componentName: 'Металл Холбогч',
    shortLabel: 'ХОЛБОГЧ',
    subtitle: 'CNC зүсэлттэй зэвэрдэггүй ган портууд',
    description: 'Агаар битүүмжлэх силикон жийрэгтэй гурвалсан дээд портууд. Зүүн талд даралт гаргах босоо хавхлаг, баруун талд хоолойн 90° тохойн холбогчтой.',
    material: '304 Эмнэлгийн зэрэглэлийн зэвэрдэггүй ган',
    specs: 'Давхар O-Ring силикон жийрэг · 100% агаар битүүмжлэл',
    animationType: 'descend-dock',
    order: 2,
  },
  {
    id: 'stem',
    stepNumber: 3,
    title: 'Дотоод Хоолой (Stem)',
    componentName: 'Дотоод Хоолой',
    shortLabel: 'ДОТООД ХООЛОЙ',
    subtitle: 'Төв агаарын урсгалын металл хоолой',
    description: 'Усанд шууд дүрэгдэх зэвэрдэггүй ган гол хоолой. Агаарын урсгалын эсэргүүцлийг тэглэж, ямар ч саадгүй зөөлөн соролт үүсгэнэ.',
    material: 'Austenitic 304 Зэвэрдэггүй ган',
    specs: '14мм дотоод диаметр · Зэврэлтэд тэсвэртэй өнгөлгөө',
    animationType: 'vertical-slide-center',
    order: 3,
  },
  {
    id: 'diffuser',
    stepNumber: 4,
    title: 'Пүршин Диффузер (2 ширхэг)',
    componentName: 'Пүршин Диффузер',
    shortLabel: 'ДИФФУЗЕР',
    subtitle: 'Чимээ дарагч хос пүршин систем',
    description: 'Цэнхэр өнгийн уян пүршээр ороосон зэвэрдэггүй ган хос саваа. Агаарын бөмбөлгийг жижиглэн сарниулж, сорох чимээг 85% хүртэл бууруулна.',
    material: 'Ган голч & Цэнхэр спираль пүрш',
    specs: '-85% бөмбөлгийн дуу намсгагч · Хоёр талт тэнцвэр',
    animationType: 'dual-submerge',
    order: 4,
  },
  {
    id: 'water',
    stepNumber: 5,
    title: 'Усны Тасалгаа',
    componentName: 'Усан Шүүлтүүр',
    shortLabel: 'УС',
    subtitle: 'Хөргөлт ба тунгалаг шүүлтүүрийн бүс',
    description: 'W их биеийн доод тасалгаанд ус дүүрч, утааг шууд хүйтнээр шүүн хөргөнө. Доороос нь цацрах цэнхэр LED гэрэлд усны бичил бөмбөлгүүд гэрэлтэн үзэгдэнэ.',
    material: 'Давхар акрилик усан бүс',
    specs: 'Зөвлөх хэмжээ: 450-500мл хүйтэн эсвэл мөстэй ус',
    animationType: 'fluid-fill-rise',
    order: 5,
  },
  {
    id: 'plate',
    stepNumber: 6,
    title: 'Утаат Шилэн Таваг',
    componentName: 'Шилэн Таваг',
    shortLabel: 'ТАВАГ',
    subtitle: 'Мөнгөлөг хүрээтэй үнсний таваг',
    description: 'Мөнгөлөг хром металл хүрээтэй, 600°C хүртэл халуунд тэсвэртэй бараан туяат хатаасан шилэн таваг. Нүүрсний үнсийг найдвартай барина.',
    material: 'Боросиликат халуунд тэсвэртэй шил & Хром хүрээ',
    specs: '210мм диаметр · 5мм зузаан хатаасан шил',
    animationType: 'descend-seat',
    order: 6,
  },
  {
    id: 'bowl',
    stepNumber: 7,
    title: 'Талст Болор Аяга',
    componentName: 'Болор Аяга',
    shortLabel: 'BOWL / АЯГА',
    subtitle: 'Алмазан зүсэлттэй амт хадгалагч аяга',
    description: 'Олон талст хээтэй, зузаан болор шилээр урласан. Амтлагчийн халалтыг жигд барьж, шатах үнэр, металлын амт оруулахгүйгээр цэвэр амтыг хадгална.',
    material: 'Хүнд талст болор шил',
    specs: '20-25гр амтлагчийн багтаамж · Дулаан жигд хуваарилалт',
    animationType: 'drop-align-top',
    order: 7,
  },
  {
    id: 'hose',
    stepNumber: 8,
    title: 'Цантай Силикон Хоолой',
    componentName: 'Силикон Хоолой',
    shortLabel: 'ХООЛОЙ',
    subtitle: 'Хүнсний зэрэглэлийн уян хоолой',
    description: 'Матт цагаан тунгалаг өнгөтэй, нугаларч хугарахгүй санах ойтой уян силикон. Үнэр шингэхгүй, усаар угааж цэвэрлэхэд маш хялбар.',
    material: 'Эмнэлгийн зэрэглэлийн силикон',
    specs: '1.5м урт · Тоос татахгүй анти-статик гадаргуу',
    animationType: 'curve-connect',
    order: 8,
  },
  {
    id: 'mouthpiece',
    stepNumber: 9,
    title: 'Өнгөлгөөт Металл Амны Хошуу',
    componentName: 'Металл Амны Хошуу',
    shortLabel: 'АМНЫ ХОШУУ',
    subtitle: 'Эргономик ховил бүхий бариул',
    description: 'CNC токариар өндөр нарийвчлалтай боловсруулсан, гарт барихад эвтэйхэн ховилтой зэвэрдэггүй ган бариул. Тэнцвэртэй, чамин тансаг мэдрэмж төрүүлнэ.',
    material: '304 Зэвэрдэггүй ган өнгөлгөө',
    specs: '300мм урт · 185гр төгс тэнцвэрт жин',
    animationType: 'horizontal-attach',
    order: 9,
  },
];

export const INITIAL_FEATURES: FeatureData[] = [
  {
    id: 'crystal-bowl',
    title: 'БОЛОР АЯГА',
    tagline: 'Халалтыг Төгс Хадгалах Технологи',
    highlight: 'Алмазан талст шилэн хийц',
    description: 'Өндөр хугарлын илтгэгчтэй болор шилээр урласан. Амтлагчийн жинхэнэ байгалийн амтыг огт өөрчлөхгүйгээр урт хугацаанд тогтвортой барина.',
    statNumber: '100%',
    statLabel: 'Амтын Цэвэр Байдал',
    iconName: 'Gem',
    image: '/src/assets/images/hookah_crystal_bowl_1791448601777.jpg',
    order: 1,
  },
  {
    id: 'acrylic-body',
    title: 'ПРЕМИУМ АКРИЛИК ИХ БИЕ',
    tagline: 'W Хэлбэрийн Өвөрмөц Архитектур',
    highlight: '12мм зузаан цутгамал PMMA',
    description: 'Хагарч гэмтэхгүй цутгамал оптик акриликийг W хэлбэрээр цоо шинээр зохион бүтээсэн. Усны гадаргуутай харьцах талбайг нэмэгдүүлж, хөргөлтийг 2 дахин хурдасгана.',
    statNumber: '12мм',
    statLabel: 'Цутгамал Ханын Зузаан',
    iconName: 'Shield',
    image: '/src/assets/images/hookah_hero_cyan_1791448575618.jpg',
    order: 2,
  },
  {
    id: 'led-lighting',
    title: 'LED ГЭРЭЛТҮҮЛЭГ',
    tagline: 'Олон Өнгийн Биолюминесцент Суурь',
    highlight: 'Утасгүй удирдлагатай LED систем',
    description: 'Акрилик их биеийн доод суурьт суурилсан хүчирхэг LED гэрэл усаар дамжин туяарч, орчны уур амьсгалыг гайхалтай футурист өнгөөр дүүргэнэ.',
    statNumber: '16M',
    statLabel: 'Өнгө Хувиргах Боломж',
    iconName: 'Lightbulb',
    order: 3,
  },
  {
    id: 'spring-diffuser',
    title: 'ПҮРШИН ДИФФУЗЕР',
    tagline: 'Хос Пүршт Чимээ Дарагч',
    highlight: 'Цэнхэр уян пүршээр ороосон голч',
    description: 'Энгийн ганц диффузерээс ялгаатай нь хоёр тасалгаат пүршин систем нь том бөмбөлгийг олон сая жижиг хөөс болгон задалж, соролтын чимээг 85% намсгана.',
    statNumber: '-85%',
    statLabel: 'Бөмбөлгийн Дуу Намсалт',
    iconName: 'Activity',
    order: 4,
  },
  {
    id: 'smooth-airflow',
    title: 'ЗӨӨЛӨН УРСГАЛ',
    tagline: 'Эсэргүүцэлгүй Агаарын Динамик',
    highlight: '14мм өргөн диаметртэй ган суваг',
    description: 'Дотоод хоолойн өргөн диаметр болон агаар гаргах өндөр нарийвчлалтай хавхлаг нь ямар ч ачаалалгүй, маш хөнгөхөн, өтгөн цагаан утаа гаргах нөхцөлийг бүрдүүлнэ.',
    statNumber: '0.04с',
    statLabel: 'Агшин Зуурын Соролтын Хариу',
    iconName: 'Wind',
    order: 5,
  },
];

export const INITIAL_WEBSITE_CONTENT: WebsiteContentData = {
  heroKicker: 'AURA W ЦУВРАЛ · ОПТИК АКРИЛИК · ЭСЭРГҮҮЦЭЛГҮЙ СОРОЛТ',
  heroTitle: 'HOOKAH-Г ШИНЭЭР МЭДЭР',
  heroSubtitle: 'Орчин үеийн загвар. Зөөлөн, тааламжтай мэдрэмж.',
  heroBadge1: 'Цутгамал Оптик PMMA',
  heroBadge2: 'Хос Пүршт Чимээ Дарагч',
  heroBadge3: 'Алмазан Талст Болор',
  scrollExploreText: 'ДООШ ГҮЙЛГЭЖ ТАНИЛЦАХ ↓',
  activationTitle: 'ЭХЛҮҮЛЭХЭД БЭЛЭН',
  activationSubtitle: 'ТАНСАГ МЭДРЭМЖ ЭХЭЛЛЭЭ',
  activationTagline: 'ДУЛААНЫ ХАЛАЛТ БА АСААЛТ',
  activationDescription: 'Болор аяганд халаагч нүүрс жигд халж, тасалгааны температурт утаа өтгөрөн бэлэн болно.',
  explodedTitle: 'ЗАДАЛСАН ТЕХНИК ХАРАГДАЦ',
  explodedSubtitle: 'БҮХ БҮРДЭЛ ХЭСГҮҮДИЙН НАРИЙВЧЛАЛ',
  explodedDescription: 'Хэсэг бүрийг CNC тоног төхөөрөмжөөр нарийн боловсруулсан. Бүрдэл хэсэг дээр дарж материалын стандартыг харна уу.',
  featuresTitle: 'ТӨГС БОЛОВСРУУЛСАН ИННОВАЦИ',
  featuresSubtitle: 'ҮЙЛДВЭРЛЭЛИЙН ДИЗАЙНЫ ОНЦЛОГ',
  featuresDescription: 'Миллиметр тутам нь халалтын тогтвортой байдал, нам гүм байдал, амтын тод илэрхийллийг дээд зэргээр хангах зориулалттай.',
  manualTitle: 'ХЭРЭГЛЭХ ЗААВАР',
  manualSubtitle: 'АШИГЛАХ 6 АЛХАМ',
  manualDescription: 'Хүйтэн ус хийхээс эхлээд гэрлээ асааж амралт мэдрэх хүртэлх энгийн, тодорхой үе шатууд.',
  finalTitle: 'ТАНЫ HOOKAH. ТАНЫ МЭДРЭМЖ.',
  finalSubtitle: 'ТОДОРХОЙЛОХ ДЭЭД ХУВИЛБАР',
  finalDescription: 'Уран баримлын акрилик геометр. Мэс заслын зэрэглэлийн зэвэрдэггүй ган. Амьсгал бүрт урьд өмнө байгаагүй зөөлөн мэдрэмж.',
  ctaText: 'ЗАГВАРУУДТАЙ ТАНИЛЦАХ',
  footerDescription: 'Чимээгүй агаарын шүүлтүүр, амтны төгс чанарыг хангах зорилгоор бүтээгдсэн архитектурын PMMA акрилик hookah систем.',
  contactEmail: 'contact@aurahookah.mn',
  contactPhone: '+976 8811-2233',
};

export const INITIAL_GALLERY: GalleryItem[] = [
  {
    id: 'gal-1',
    image: '/src/assets/images/hookah_hero_cyan_1791448575618.jpg',
    title: 'AURA W Бүрэн Угсарсан Байдал',
    description: 'Цэнхэр акрилик их бие болон өнгөлөг цэнхэр гэрэлтүүлэгтэй студийн зураг.',
    displayOrder: 1,
  },
  {
    id: 'gal-2',
    image: '/src/assets/images/hookah_crystal_bowl_1791448601777.jpg',
    title: 'Талст Болор Аяганы Ойрын Зураг',
    description: 'Өндөр нарийвчлалтай алмазан талст зүсэлт болон халалтын бүсийн деталь.',
    displayOrder: 2,
  },
];

export const INITIAL_ORDERS: OrderItem[] = [
  {
    id: 'ORD-1001',
    customerName: 'Бат-Эрдэнэ Т.',
    phone: '9911-2233',
    product: 'AURA W Премиум Hookah Багц (Electric Cyan)',
    quantity: 1,
    price: 890000,
    status: 'new',
    createdDate: '2026-10-08 14:20',
    address: 'Улаанбаатар хот, ХУД, 15-р хороо, Ривер Гарден 402',
    note: 'Хүргэлтийн өмнө утсаар залгана уу.',
  },
  {
    id: 'ORD-1002',
    customerName: 'Энхжин М.',
    phone: '9512-4455',
    product: 'AURA W Премиум Hookah Багц (Electric Cyan)',
    quantity: 2,
    price: 1780000,
    status: 'confirmed',
    createdDate: '2026-10-07 18:45',
    address: 'Улаанбаатар хот, СБД, 1-р хороо',
    note: 'Бэлгэнд өгөх тул хайрцаг гэмтээгүй байх шаардлагатай.',
  },
  {
    id: 'ORD-1003',
    customerName: 'Тэмүүлэн Б.',
    phone: '8800-9988',
    product: 'AURA W Премиум Hookah Багц (Electric Cyan)',
    quantity: 1,
    price: 890000,
    status: 'delivered',
    createdDate: '2026-10-06 11:15',
    address: 'Улаанбаатар хот, БЗД, 26-р хороо',
  },
];

export const INITIAL_MESSAGES: CustomerMessage[] = [
  {
    id: 'MSG-201',
    customerName: 'Төгөлдөр',
    phone: '9988-7766',
    email: 'tuguldur@gmail.com',
    message: 'Сайн байна уу, хөдөө орон нутаг руу унаанд хүргэж өгөх боломжтой юу?',
    createdDate: '2026-10-08 12:30',
    status: 'unread',
    source: 'website',
  },
  {
    id: 'MSG-202',
    customerName: 'Анударь',
    phone: '9191-2323',
    message: 'Нэмэлт нүүрс болон амтлагч хамт захиалж болох уу? Мөн өнгө сонгож болох уу?',
    createdDate: '2026-10-07 19:10',
    status: 'replied',
    source: 'messenger',
  },
];

export const INITIAL_SETTINGS: AppSettings = {
  storeName: 'AURA W Mongolia',
  currency: '₮',
  contactPhone: '+976 8811-2233',
  contactEmail: 'contact@aurahookah.mn',
  facebookPageId: 'aurahookah.mongolia',
  supabaseEnabled: false,
  metaWebhookEnabled: false,
  primaryColor: '#00F2FE',
};
